//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/proto_islandsurvival.proto
namespace proto_islandsurvival
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLogin")]
  public partial class CSLogin : global::ProtoBuf.IExtensible
  {
    public CSLogin() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _passwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passwd
    {
      get { return _passwd; }
      set { _passwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCLogin")]
  public partial class SCLogin : global::ProtoBuf.IExtensible
  {
    public SCLogin() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSRegist")]
  public partial class CSRegist : global::ProtoBuf.IExtensible
  {
    public CSRegist() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _passwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passwd
    {
      get { return _passwd; }
      set { _passwd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCRegist")]
  public partial class SCRegist : global::ProtoBuf.IExtensible
  {
    public SCRegist() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBRoomInfo")]
  public partial class PBRoomInfo : global::ProtoBuf.IExtensible
  {
    public PBRoomInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _have;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"have", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int have
    {
      get { return _have; }
      set { _have = value; }
    }
    private int _limit;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int limit
    {
      get { return _limit; }
      set { _limit = value; }
    }
    private int _game_mode;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"game_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_mode
    {
      get { return _game_mode; }
      set { _game_mode = value; }
    }
    private int _team_mode;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"team_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team_mode
    {
      get { return _team_mode; }
      set { _team_mode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PBDetailRoomInfo")]
  public partial class PBDetailRoomInfo : global::ProtoBuf.IExtensible
  {
    public PBDetailRoomInfo() {}
    
    private readonly global::System.Collections.Generic.List<string> _players = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> players
    {
      get { return _players; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _team_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"team_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> team_id
    {
      get { return _team_id; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _player_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> player_id
    {
      get { return _player_id; }
    }
  
    private int _game_option;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"game_option", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_option
    {
      get { return _game_option; }
      set { _game_option = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSChangeTeam")]
  public partial class CSChangeTeam : global::ProtoBuf.IExtensible
  {
    public CSChangeTeam() {}
    
    private int _team_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"team_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int team_id
    {
      get { return _team_id; }
      set { _team_id = value; }
    }
    private int _game_option = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"game_option", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int game_option
    {
      get { return _game_option; }
      set { _game_option = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSPullAllRoomInfo")]
  public partial class CSPullAllRoomInfo : global::ProtoBuf.IExtensible
  {
    public CSPullAllRoomInfo() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCPullAllRoomInfo")]
  public partial class SCPullAllRoomInfo : global::ProtoBuf.IExtensible
  {
    public SCPullAllRoomInfo() {}
    
    private readonly global::System.Collections.Generic.List<PBRoomInfo> _rooms = new global::System.Collections.Generic.List<PBRoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"rooms", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PBRoomInfo> rooms
    {
      get { return _rooms; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSCreateRoom")]
  public partial class CSCreateRoom : global::ProtoBuf.IExtensible
  {
    public CSCreateRoom() {}
    
    private int _game_mode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"game_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int game_mode
    {
      get { return _game_mode; }
      set { _game_mode = value; }
    }
    private int _team_mode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"team_mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int team_mode
    {
      get { return _team_mode; }
      set { _team_mode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCCreateRoom")]
  public partial class SCCreateRoom : global::ProtoBuf.IExtensible
  {
    public SCCreateRoom() {}
    
    private bool _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _room_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSJoinRoom")]
  public partial class CSJoinRoom : global::ProtoBuf.IExtensible
  {
    public CSJoinRoom() {}
    
    private int _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCJoinRoom")]
  public partial class SCJoinRoom : global::ProtoBuf.IExtensible
  {
    public SCJoinRoom() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSPlayerExitRoom")]
  public partial class CSPlayerExitRoom : global::ProtoBuf.IExtensible
  {
    public CSPlayerExitRoom() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCPlayerExitRoom")]
  public partial class SCPlayerExitRoom : global::ProtoBuf.IExtensible
  {
    public SCPlayerExitRoom() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCPullOneRoomDetail")]
  public partial class SCPullOneRoomDetail : global::ProtoBuf.IExtensible
  {
    public SCPullOneRoomDetail() {}
    
    private PBDetailRoomInfo _room_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PBDetailRoomInfo room_info
    {
      get { return _room_info; }
      set { _room_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSReadyToStart")]
  public partial class CSReadyToStart : global::ProtoBuf.IExtensible
  {
    public CSReadyToStart() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCGameLoading")]
  public partial class SCGameLoading : global::ProtoBuf.IExtensible
  {
    public SCGameLoading() {}
    
    private int _rand;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"rand", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rand
    {
      get { return _rand; }
      set { _rand = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLoadSucceed")]
  public partial class CSLoadSucceed : global::ProtoBuf.IExtensible
  {
    public CSLoadSucceed() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCGameStart")]
  public partial class SCGameStart : global::ProtoBuf.IExtensible
  {
    public SCGameStart() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCPlayerExitGame")]
  public partial class SCPlayerExitGame : global::ProtoBuf.IExtensible
  {
    public SCPlayerExitGame() {}
    
    private int _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSChoseRole")]
  public partial class CSChoseRole : global::ProtoBuf.IExtensible
  {
    public CSChoseRole() {}
    
    private int _role_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCChoseRole")]
  public partial class SCChoseRole : global::ProtoBuf.IExtensible
  {
    public SCChoseRole() {}
    
    private int _role_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"role_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int role_id
    {
      get { return _role_id; }
      set { _role_id = value; }
    }
    private int _player_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCFrameMess")]
  public partial class SCFrameMess : global::ProtoBuf.IExtensible
  {
    public SCFrameMess() {}
    
    private int _operation;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"operation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int operation
    {
      get { return _operation; }
      set { _operation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSMove")]
  public partial class CSMove : global::ProtoBuf.IExtensible
  {
    public CSMove() {}
    
    private int _dir;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCMove")]
  public partial class SCMove : global::ProtoBuf.IExtensible
  {
    public SCMove() {}
    
    private int _dir;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private int _player_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"player_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int player_id
    {
      get { return _player_id; }
      set { _player_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSGamePause")]
  public partial class CSGamePause : global::ProtoBuf.IExtensible
  {
    public CSGamePause() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCGamePause")]
  public partial class SCGamePause : global::ProtoBuf.IExtensible
  {
    public SCGamePause() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSSkill")]
  public partial class CSSkill : global::ProtoBuf.IExtensible
  {
    public CSSkill() {}
    
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private float _pos_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private int _target_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SCSkill")]
  public partial class SCSkill : global::ProtoBuf.IExtensible
  {
    public SCSkill() {}
    
    private int _skill_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"skill_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skill_id
    {
      get { return _skill_id; }
      set { _skill_id = value; }
    }
    private float _pos_x;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pos_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_x
    {
      get { return _pos_x; }
      set { _pos_x = value; }
    }
    private float _pos_z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float pos_z
    {
      get { return _pos_z; }
      set { _pos_z = value; }
    }
    private int _target_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"target_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target_id
    {
      get { return _target_id; }
      set { _target_id = value; }
    }
    private int _attacker_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"attacker_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attacker_id
    {
      get { return _attacker_id; }
      set { _attacker_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSHeartbeat")]
  public partial class CSHeartbeat : global::ProtoBuf.IExtensible
  {
    public CSHeartbeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSGameEnd")]
  public partial class CSGameEnd : global::ProtoBuf.IExtensible
  {
    public CSGameEnd() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}